export const ADD_TODO = "addTodo"
export const UPDATE_NEW_TODO = "updateNewTodo"
export const SET_COMPLETION_STATE = "setCompletionState"
export const REMOVE_TODO = "removeTodo"
export const UPDATE_TODO_TEXT = "updateTodoText"
export const CLEAR_COMPLETED = "clearCompleted"
